module.exports = {
    TOKEN_ERROR: "Token not correct.",
    NO_TOKEN: "Token required to access API.",
    INVALID_BODY: "Request body is invalid.",
    DATA_SAVED: "Request completed and data saved.",
    DATA_RETRIEVED: "Request completed and data retrieved.",
    DATA_DELETED: "Request completed and data deleted.",
    DATA_UPDATED: "Request completed and data updated.",
    DATA_NOT_FOUND: "Data not found against this query",
    PASSOWRD_MISMATCH: "Old password didn't match",
    PASSOWRD_ERROR: "Password didn't match",
    PASSWORD_UPDATED: "Password has been updated",
    USER_NOTFOUND: "User doesn't exist",
    USER_SIGNEDIN: "User is signed-in",
    USER_LOGGEDOUT: "User is logged-out",
    ADMIN: "ADM",
    SEEDING: "Seeding done successfully",
    SEDDING_FAILURE: "Sededing Failed",
    NO_SUBSCRIPTION: "No subcription available",
    PASSWORD_EMAIL: "Email sent for password reset.",
    INVALID_COUPON: "Invalid coupon",
    DATA_EXIST: "Data already exist can not be duplicate",
};
